id: P009588
initial_creation_type: ocr
source_metadata:
  id: bdr:W23682
  title: རང་བཞིན་རྫོགས་པ་ཆེན་པོའི་ཆོས་འབྱུང་རིག་འཛིན་བརྒྱུད་པའི་རྣམ་ཐར་ངོ་མཚར་ནོར་བུ་བཻ་ཌཱུརྱའི་ཕྲེང་བ
  author: ''
  volumes: {}
