id: P009588
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W23682
  title: རང་བཞིན་རྫོགས་པ་ཆེན་པོའི་ཆོས་འབྱུང་རིག་འཛིན་བརྒྱུད་པའི་རྣམ་ཐར་ངོ་མཚར་ནོར་བུ་བཻ་ཌཱུརྱའི་ཕྲེང་བ
  author: ''
  volumes:
    fa5875dae76549eba544ec27adfafb09:
      image_group_id: I2429
      title: ''
      volume_number: 1
      total_pages: 672
      base_file: v001.txt
    b605a9f02f1a4597b329ef22bda32f32:
      image_group_id: I2430
      title: ''
      volume_number: 2
      total_pages: 708
      base_file: v002.txt
