id: I4F92CF2C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T12:59:54+00:00'
last_modified: '2022-06-08T12:05:34.185071+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23682
  title: རང་བཞིན་རྫོགས་པ་ཆེན་པོའི་ཆོས་འབྱུང་རིག་འཛིན་བརྒྱུད་པའི་རྣམ་ཐར་ངོ་མཚར་ནོར་བུ་བཻ་ཌཱུརྱའི་ཕྲེང་བ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    223B:
      image_group_id: I2429
      title: ''
      total_pages: 672
      order: 1
      base_file: 223B.txt
    2D63:
      image_group_id: I2430
      title: ''
      total_pages: 708
      order: 2
      base_file: 2D63.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
