id: I4F92CF2C
legacy_id: P009588
ocr_import_info:
  bdrc_scan_id: W23682
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T12:55:45'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T01:50:55.794146+00:00'
last_modified: 2022-09-02 09:52:09.935578
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23682
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23682
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྫོགས་ཆེན་ཆོས་འབྱུང་།
  author: སྨྱོ་ཤུལ་མཁན་པོ་འཇམ་དབྱངས་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.8195041306164847
  ocr_word_median_confidence_index: 0.9100000262260437
quality: null
bases:
  I2430:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2430
      total_pages: 708
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I2430.txt
    statistics:
      ocr_word_median_confidence_index: 0.8999999761581421
      ocr_word_mean_confidence_index: 0.8048773592946269
    legacy_id: v002
  I2429:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2429
      total_pages: 672
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2429.txt
    statistics:
      ocr_word_median_confidence_index: 0.9300000071525574
      ocr_word_mean_confidence_index: 0.8342091299867253
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
